version: 2.1

jobs:
  test:
    docker:
      - image: busybox
    steps:
      - checkout
      - run:
          name: hello
          command: echo "hello"

workflows:
  test_my_app:
    jobs:
      - test

usage:
  version: 2.1
  orbs:
  kubernetes-gke-publish: saudeid/kubernetes-gke-publish@0.0.3

  workflows:
    test_my_app:
      jobs:
        - test
