version: 2.1


jobs:
  test:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: hello
          command: echo $cluster_kubernetes >> /tmp/kubernetes.credentias
      - run:
          name: install kubectl
          command: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - run:
          name: check-kubernetes
          command: kubectl version --client
      - run:
          name: Namespaces
          command: kubectl get namespaces --kubeconfig="base64:$cluster_kubernetes"

workflow:
  build:
    jobs:
      - test

usage:
  version: 2.1
  orbs:
    kubernetes-gke-publish: saudeid/kubernetes-gke-publish@0.0.16

  workflows:
    build:
      jobs:
        - kubernetes-gke-publish/test:
            context:
            - dev
    
