version: 2.1

workflows:
  gke:
  jobs:
    - build-deploy:
        context:
        - dev


jobs:
  build-deploy:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: orb
          command: |
            git clone 
      - run:
          name: hello
          command: ls
          dir: echo $cluster_kubernetes
      


usage:
  version: 2.1
  orbs:
  kubernetes-gke-publish: saudeid/kubernetes-gke-publish@0.0.12

  workflows:
    - kubernetes-gke-publish/gke
