version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: hello
          command: ls

workflows:
  test_my_app:
    jobs:
      - test

usage:
  version: 2.1
  orbs:
  kubernetes-gke-publish: saudeid/kubernetes-gke-publish@0.0.8

  workflows:
    test_my_app:
      jobs:
        - test
