version: 2.1


jobs:
  test:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: orb
          command: |
            git clone 
      - run:
          name: hello
          command: echo $CLUSTER_KUBERNETES
          dir: ./src/

workflow:
  build:
    jobs:
      - test

usage:
  version: 2.1
  orbs:
    kubernetes-gke-publish: saudeid/kubernetes-gke-publish@0.0.16

  workflows:
    build:
      jobs:
        - kubernetes-gke-publish/test:
            context:
            - dev
    
