version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: orb
          command: |
            git clone 
      - run:
          name: hello
          command: ls
          dir: ./src/

usage:
  version: 2.1
  orbs:
  kubernetes-gke-publish: saudeid/kubernetes-gke-publish@0.0.11

  workflows:
    test_my_app:
      jobs:
        - kubernetes-gke-publish/test
