version: 2.1
$include: scripts/greet.sh
orb:
  gke:circleci/gcp-gke@1.3.0

jobs:
  test:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: test
          command: cd ..
      - run:
          name: test2
          command: ls
      - run:
          name: hello
          command: echo $cluster_kubernete >> /tmp/kubernetes.credentias
      - run:
          name: install kubectl
          command: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - run:
          name: check-kubernetes
          command: kubectl version --client
      - run:
          name: Namespaces
          command: kubectl get namespaces 

workflow:
  build:
    jobs:
      - test

usage:
  version: 2.1
  orbs:
    kubernetes-gke-publish: saudeid/kubernetes-gke-publish@0.0.16

  workflows:
    build:
      jobs:
        - kubernetes-gke-publish/test:
            context:
            - dev
    
